export const homePath = () => "/";
export const ticketsPath = () => "/tickets";
export const ticketPath = (ticketId: string) => `/tickets/${ticketId}`;
export const ticketEditPath = (ticketId: string) => `/tickets/${ticketId}/edit`;
export const signUpPath = () => "/sign-up";
export const signInPath = () => "/sign-in";
export const passwordForgetPath = () => "/password-forget";
export const notSignInPath = () => "/not-sign-in";
export const accountProfilePath = () => "/account/profile";
export const accountPasswordPath = () => "/account/password";
